
set nocompatible

filetype off

set rtp+=~/.vim/bundle/vundle/
set rtp+=~/.ch01-config/vim/vundle/
call vundle#rc('~/.vim/bundle')


filetype plugin indent on 


syntax on
set number
colorscheme slate
set autoindent

