
set nocompatible

filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" " required! 
Bundle 'gmarik/vundle'

filetype plugin indent on 
" required!


syntax on
set number
colorscheme slate
set autoindent

